development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weatherbase
  pool: 5
  username:
  password:
  host: